apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ?namespace
  name: ?module_name
spec:
  selector:
    matchLabels:
      app: ?module_name
  template:
    metadata:
      labels:
        app: ?module_name
    spec:
      containers:
        - name: ?module_name
          image: ?image_path
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: SPRING_ENV
              value: 'dev,core'
            - name: NACOS_NAMESPACE
              value: wukong_dev
      imagePullSecrets:
        - name: aliyun-acr


---

apiVersion: v1
kind: Service
metadata:
  name: ?module_name
  namespace: ?namespace
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: ?module_name