apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ?namespace
  name: ?module_name
  labels:
    app: ?module_name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ?module_name
  template:
    metadata:
      labels:
        app: ?module_name
    spec:
      containers:
        - name: ?module_name
          image: ?image_path
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources:
            limits:
              memory: "600Mi"
              cpu: "500m"
            requests:
              memory: "250Mi"
              cpu: "100m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
      imagePullSecrets:
        - name: harbor-secret

---

apiVersion: v1
kind: Service
metadata:
  name: ?module_name
  namespace: ?namespace
  labels:
    app: ?module_name
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: ?module_name

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ?module_name
  namespace: ?namespace
  labels:
    app: ?module_name
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: ?module_name.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ?module_name
                port:
                  number: 80
